version: '3.9'

services:
  backend:
    image: prj/backend:latest
    build: 
      context: ./backend
      dockerfile: ../backend.Dockerfile
    command: python /code/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: